### ISSUE TITLE
Simplified Chinese is not working in the BTM plot (bigram plot)

### ISSUE THREAD

**Issue by DQKF** [bnosac/textplot#4]
I have some problems with the font issues as I use R Package BTM.
As one may see in the graph as attached, "Simplified Chinese" is not working as plotted.

Here's the plot code:
M02<-plot(model02, top_n = 10, family = "SimSun",
     title = "BTM model", subtitle = "R packages in the NLP/Machine Learning task views",
     labels = c("Topic01", "Topic02", "Topic03",
                "Topic04", "Topic05",
                "Topic06", "Topic07",
                "Topoc08", "Topic09", "Topic10", "Topic11", "Topic12", "Topic13", "Topic14", "Topic15"))

Text mining in Simplified Chinese.
<img width="752" alt="螢幕快照 2021-02-22 00 18 15" src="https://user-images.githubusercontent.com/76861284/108838440-9799f080-760e-11eb-9ccb-3eee9dfeede1.png">

![XJP_neg_BTM](https://user-images.githubusercontent.com/76861284/108838820-227aeb00-760f-11eb-88e9-68abb758b81e.png)

**Comment by jwijffels** [comment]
Hello @DQKF 
Can you share your `model02 `object such that I can reproduce this locally `save(model02, file = "model02.RData")` or provide a reproducible example with some simplified chinese terms in there showing this behaviour.

**Comment by jwijffels** [comment]
I'm not sure what the cause of this is. This is what I'm getting when applying on your model object:
![Rplot](https://user-images.githubusercontent.com/1710810/109010055-9f5da180-76af-11eb-8c36-81849b6eef78.png)

I'm running this on Windows. Maybe you are on another system?
```
library(BTM)
library(textplot)
load("C:/Users/Jan/Desktop/model02.RData")
plot(model02, biterms = model02$biterms$biterms, top_n = 10, family = "SimSun")
```

**Comment by DQKF** [comment]
I am running all the jobs on the Apple IOS system, pretty weird!
Thanks anyway!

**Comment by jwijffels** [comment]
This plotting functionality relies on the ggraph package and the ggplot2 package. Maybe this is the solution to your question: https://community.rstudio.com/t/chinese-characters-in-ggplot-on-macos/4429

**Comment by jwijffels** [comment]
Maybe you need to set this upfront:

```
library(BTM)
library(textplot)
library(ggraph)
library(ggforce)
library(concaveman)
library(ggplot2)
library(igraph)
load("C:/Users/Jan/Desktop/model02.RData")

theme <- theme_get()
theme$text$family <- "STFangsong"
theme_set(theme)

plot(model02, biterms = model02$biterms$biterms, top_n = 10)
```

**Comment by DQKF** [comment]
I just add   > showtext_auto(),  and everything's fine with the graph!
Thanks, Dr. Wijffels!
![show-text-auto](https://user-images.githubusercontent.com/76861284/109021964-55e47500-76f6-11eb-8b16-c45c394c920d.png)

**Comment by jwijffels** [comment]
Ok great. Good to know.
