### ISSUE TITLE
[textplot_dependencyparser.default] Add layout argument

### ISSUE THREAD

**Issue by discoleo** [bnosac/textplot#8]
# Function textplot_dependencyparser.default

Add a layout argument:
- default value: layout = "linear";

## Code changes
```
[...]
ggraph::ggraph(g, layout = layout) +
[...]
```

## Example

Problem:
- the plot fails ugly with very long sentences.;
- example uses the Results section of an abstract from Pubmed (PMID = 35420756);
- I have uploaded a set of 1200 Pubmed abstracts on Github, see file [Example_Abstracts_Title_Pubmed.csv](https://github.com/discoleo/R/blob/master/TextMining/Pubmed/Example_Abstracts_Title_Pubmed.csv)
```
abs1 = "RESULTS: Our scan of Canadian government and university web pages found that  
          universities similarly created one main page for COVID-19 updates and information
          and linked to public sector agencies as a main resource, and mainly differed in  
          their provincial and local sources for obtaining information. They also differed 
          in their strategies for communicating and displaying this information to their   
          respective students."
txtSection = "(?i)^(?:Objectives|Results|Conclusions)\\:"
tmp = sub(txtSection, "", abs1);
# udmodel = english-ewt;
ann = udpipe_annotate(udmodel, x = tmp)
ann = as.data.frame(ann, detailed = TRUE)

# Sentence
idS = 1
textplot_dependencyparser(ann[ann$sentence_id == idS,])
```

**Comment by discoleo** [comment]
# Basic code for Multi-line Layout

Note:
- the split may not be optimal;
- TODO: fix width and text-overlap issues;

```
layoutSplit = function(x, y=NULL, nr=1, scale=c(2,30)) {
	len = nchar(x);
	if( ! is.null(y)) len = pmax(len, nchar(y));
	if(nr > 1) {
		nm = length(len) %% nr;
		if(nm != 0) len = c(len, rep(0, nr - nm));
	}
	nc  = length(len) %/% nr;
	len = matrix(len, nrow=nr);
	len = apply(len, 1, cumsum);
	dim(len) = NULL;
	len = len * scale[1];
	xdf = data.frame(
		x = len,
		y = rep(seq(nr, 1, by=-1) * scale[2], each=nc));
	return(xdf)
}
```

**Comment by jwijffels** [comment]
We can certainly add the layout argument in the function definition so that you can pass whichever on.

Note getting this currently with your layoutSplit

![image](https://user-images.githubusercontent.com/1710810/168979226-66072469-06bb-4487-be50-d5f1e219e32e.png)

**Comment by discoleo** [comment]
Latest version of layoutSplit:
- fixed a bug & improved layout;

Note:
- the function splits the number of words into nr rows;
- it does **not** split the number of chars evenly, nor does it optimize for head tokens;

**Comment by jwijffels** [comment]
I've added the layout argument and will upload the package to CRAN
